### ISSUE TITLE
Error when creating Policy

### ISSUE THREAD

**Issue by moh-abk** [eleven41/aws-lambda-send-ses-email#1]
Hi,

I'm getting an invalid policy name error when creating the policy.
Can you assist please.

**Comment by mwhouser** [comment]
What are you using for your policy name?

**Comment by moh-abk** [comment]
`aws-lambda-send-ses-email-policy.`

It's complaining about the line;

`"PolicyName" : "aws-lambda-send-ses-email-policy",`

**Comment by mwhouser** [comment]
Try this:

``` json
{
        "Version" : "2012-10-17",
        "Statement" : [
            {
                "Effect" : "Allow",
                "Action" : [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                ],
                "Resource" : "arn:aws:logs:*:*:*"
            },
            {
                "Effect" : "Allow",
                "Action" : [
                    "cloudwatch:PutMetricData"
                ],
                "Resource" : "*"
            },
            {
                "Effect" : "Allow",
                "Action" : [
                    "ses:SendEmail"
                ],
                "Resource" : "*"
            },
            {
                "Effect" : "Allow",
                "Action" : [
                    "s3:GetObject"
                ],
                "Resource" : "*"
            }
        ]
    }
```

**Comment by moh-abk** [comment]
Trying that now... 
Will this replace any `{{replace}}` as long as I provide `replace` in the body of the request?

**Comment by mwhouser** [comment]
The body of the request just be valid json. For example:

``` json
{
  "name": "John",
  "email": "john@example.com",
  "message": "This is my message"
}
```

**Comment by moh-abk** [comment]
How should I zip it? What should be in the root?

**Comment by mwhouser** [comment]
For step 4 of the readme, download `aws-lambda-send-ses-email-0.1.3.zip`  from here:

https://github.com/eleven41/aws-lambda-send-ses-email/releases

**Comment by moh-abk** [comment]
`START RequestId: 21ca134c-b55f-11e5-98e0-897df8c14989 Version: $LATEST
2016-01-07T16:53:10.122Z    21ca134c-b55f-11e5-98e0-897df8c14989    Event: {"name":"xxx","email":"xxx@gmail.com","message":"This is my message"}
2016-01-07T16:53:10.162Z    21ca134c-b55f-11e5-98e0-897df8c14989    SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at exports.handler (/var/task/index.js:18:18)
END RequestId: 21ca134c-b55f-11e5-98e0-897df8c14989
REPORT RequestId: 21ca134c-b55f-11e5-98e0-897df8c14989  Duration: 122.88 ms Billed Duration: 200 ms     Memory Size: 128 MB Max Memory Used: 13 MB  
Process exited before completing request`

**Comment by mwhouser** [comment]
I've noticed an issue in https://github.com/eleven41/aws-lambda-send-ses-email/blob/master/SendSesEmail/config.js:
1. Double check the "defaultSubject" property is properly quoted, and
2. Remove the extra comma (,) at the end of that property (after the last quote)

If you still have issues, paste your `config.js` file here.

**Comment by moh-abk** [comment]
All good now. Thanks for spoting those errors.

I noticed that the `"targetAddress"` is the recipients email.
As you can't edit the `config.js` when you invoke the function, I've changed the line;

```
ToAddresses: [
    config.targetAddress
```

to

```
ToAddresses: [
    event.email
```

And it works as expected. So  now from my web app. The `email` in the `payload` will be the recipient address.

**Comment by moh-abk** [comment]
Also I guess based on that I can decide to use one function for many templates and change the line;

`Key: config.templateKey` to `Key: event.templateKey` and then provide `templateKey` in my `payload`
