### ISSUE TITLE
Video tutorial

### ISSUE THREAD

**Issue by quantuminformation** [eleven41/aws-lambda-send-ses-email#4]
Would be great to have a Video tutorial on how to set this up from start to finish!

**Comment by prashantgijare** [comment]
I was thinking exactly same when I read this and got excited. At least a detailed text guide would help. If I'm successful doing this, I'm going to make and post vide of this. 

@QuantumInformation - Did you try to make it work? Do  you have any documentation?

Thanks!
~P

**Comment by quantuminformation** [comment]
I moved to firebase, AWS was to much work.
